export const SET_BLACKLIST_ADDRESS = 'blacklist/SET_HOME_ADDRESS';
export const SET_BLACKLIST_ONBOARDING_STATUS = 'blacklist/ONBOARDING_STATUS';

export const SET_LOGGING = 'map/SET_LOGGING';
export const SET_FOCUS_LOCATION = 'map/SET_FOCUS_LOCATION';
export const SET_PLACE_LOCATION = 'map/SET_PLACE_LOCATION';
export const SET_NAVIGATION_LINE_STRING = 'map/SET_NAVIGATION_LINE_STRING';

export const SET_SEARCHING_STATE = 'search/SET_SEARCHING_STATE';
